//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressionBuilder.Test.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Person {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Person() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExpressionBuilder.Test.Resources.Person", typeof(Person).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country of Birth.
        /// </summary>
        internal static string Birth_Country {
            get {
                return ResourceManager.GetString("Birth_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        internal static string Birth_Date {
            get {
                return ResourceManager.GetString("Birth_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact&apos;s Comments.
        /// </summary>
        internal static string Contacts_Comments_ {
            get {
                return ResourceManager.GetString("Contacts_Comments_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact&apos;s Type.
        /// </summary>
        internal static string Contacts_Type_ {
            get {
                return ResourceManager.GetString("Contacts_Type_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact&apos;s Value.
        /// </summary>
        internal static string Contacts_Value_ {
            get {
                return ResourceManager.GetString("Contacts_Value_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employer&apos;s Industry.
        /// </summary>
        internal static string Employer_Industry {
            get {
                return ResourceManager.GetString("Employer_Industry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employer&apos;s Name.
        /// </summary>
        internal static string Employer_Name {
            get {
                return ResourceManager.GetString("Employer_Name", resourceCulture);
            }
        }
    }
}
